### ISSUE TITLE
Incorrect colours for login screen in dark mode

### ISSUE THREAD

**Issue by wilcooo** [acristescu/OnlineGo#111] opened 2021-08-15 19:38 UTC
I like the new first app launch experience! Only it took me a while before I noticed where I had to put in my username and password. (See image below)

The fact that I'm using a blue-light filter might have made things worse.

Also, the form doesn't interact with Androids autofill framework, so I had to manually go to my password manager app. (Should I make a new issue for this feature request?)

![Screenshot_20210815-212944](https://user-images.githubusercontent.com/28764227/129490222-fd382f94-5cb9-4b4b-87a3-c3de49fa565b.png)

**Comment by fuzzthink** [comment] 2021-09-10 20:17
A normal white background was even worst. Came here to file a bug. I think it's a critical bug that may be driving 99% of your username-login users away.

**Comment by acristescu** [comment] 2021-09-11 16:30
Hi guys, thank you for your bug report. I am not sure what wrong with @wilcooo 's phone, even the Android icons look red and washed out instead of white. I can't really account for every thing people do with their rooted phones sadly...

@fuzzthink can you please provide a screenshot with your phone model? I don't quite understand the problem.

For reference, this is what it looks like on all the phones I've tried it on:

![Screenshot_20210911-172901_Online Go](https://user-images.githubusercontent.com/2835035/132954747-87ca6e8e-bab1-4de8-81c3-0ed4919512ac.jpg)

**Comment by popz73** [comment] 2021-09-11 17:02
Hi Alex,
It's a Dark Mode issue. They have their system in dark mode, and indeed I
can easily replicate the invisible fields that way as well.

Cheers
João

**Comment by acristescu** [comment] 2021-09-11 18:17
Hi Joao,

Thanks for that, I can reproduce it now. I rarely use dark mode and so I keep missing that sort of thing. If you notice anything funny in dark mode, please report it.

I will fix this in the next version.

**Comment by fuzzthink** [comment] 2021-09-11 21:10
@popz73 is right, my phone is in dark mode. It's not exactly invisible, but the difference in color is probably 1-2% at best.

**Comment by acristescu** [comment] 2021-10-02 09:45
Fixed in alpha_b375. Please reopen if there are any more issues with dark mode in onboarding.

Thanks all for reporting and providing details!

**Closed by acristescu** 2021-10-02 09:45 UTC
Labels: bug
