### ISSUE TITLE
Multiple issues when notifications disabled

### ISSUE THREAD

**Issue by alexmitrani** [acristescu/OnlineGo#163] opened 2023-08-14 16:11 UTC
Hi.

When I disabled notifications the app showed the "no connection" icon and the app user interface became unresponsive. 

The app started working again when I re-enabled notifications. 

I tried several times and tthis seemed to happen every time. 

Samsung Galaxy A14 5G, Android 13. 

Please have a look. 

Thanks

Alex

**Comment by siomy11** [comment] 2024-05-14 15:10
I know this is old but just had the same problem: Pixel 6A, Android 13.

**Comment by acristescu** [comment] 2024-05-21 13:17
Hi guys, sorry for the long absence. I have confirmed this and a fix will be released in the next version.

**Closed by acristescu** 2024-05-21 13:17 UTC

**Comment by siomy11** [comment] 2024-05-21 13:48
Thanks! Just curious, do you have a timeframe for the next version?

**Comment by acristescu** [comment] 2024-05-21 14:42
@siomy11 not sure since I have to figure out what the state of the app was when I left it 7 months ago. But there is a workaround in the meantime. You can enable the notifications (either by reinstalling the app and answering yes when prompted or from the phone settings) and then disabling the notification channel from the app settings. The end result is the same, you're not receiving notifications, but it gets you unstuck.
